
pool:
  vmImage: ubuntu-latest

variables:

  # Azure Container Registry Service Connection
  acrServiceConnection: 'acrserviceconnection'
  frontendRepository: 'credpay/frontend'
  userRepository: 'credpay/user-service'
  paymentRepository: 'credpay/payment-service'
  tag: '$(Build.BuildId)'

# =========================================================
# STAGES
# =========================================================

stages:

# =========================================================
# STAGE 1 - BUILD & PUSH DOCKER IMAGES
# =========================================================

- stage: DockerBuild
  displayName: Docker Build & Push
  jobs:

  - job: BuildPushImages
    displayName: Build Docker Images

    steps:

    - checkout: self

    #########################################################
    # FRONTEND
    #########################################################

    - task: Docker@2
      displayName: Build & Push Frontend Image

      inputs:
        command: buildAndPush
        containerRegistry: 'acrserviceconnection'
        repository: $(frontendRepository)
        dockerfile: frontend-react/dockerfile
        buildContext: frontend-react

        tags: |
          $(tag)
          latest

    #########################################################
    # USER SERVICE
    #########################################################

    - task: Docker@2
      displayName: Build & Push User Service Image

      inputs:
        command: buildAndPush
        containerRegistry: 'acrserviceconnection'
        repository: $(userRepository)
        dockerfile: user-service/dockerfile
        buildContext: user-service

        tags: |
          $(tag)
          latest

    #########################################################
    # PAYMENT SERVICE
    #########################################################

    - task: Docker@2
      displayName: Build & Push Payment Service Image

      inputs:
        command: buildAndPush
        containerRegistry: 'acrserviceconnection'
        repository: $(paymentRepository)
        dockerfile: payment-service/dockerfile
        buildContext: payment-service

        tags: |
          $(tag)
          latest

