FROM python:3.11-slim 
ENV PYTHONBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app ./app
ENV DB_USERNAME=postgres \
    DB_HOST=localhost \
    DB_PORT=5432 \
    DB_NAME=credpay
EXPOSE 8000
ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]



